server:
  port: 8084

spring:
  application:
    name: servicio_de_profesionales
    
  datasource:
    url: jdbc:oracle:thin:@udpftr6a6yrxy6ye_high?TNS_ADMIN=/app/wallet
    username: ADMIN
    password: FullStack-001
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

logging:
  level:
    org:
      hibernate: DEBUG
    com:
      zaxxer:
        hikari: DEBUG
    java:
      sql: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html