# Configuración exclusiva para Pruebas Unitarias (H2 en Memoria)
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:agenda_test_db;DB_CLOSE_DELAY=-1;MODE=Oracle
spring.datasource.username=sa
spring.datasource.password=

# H2 creará el esquema basado en tus entidades de Java de cero y lo destruirá al finalizar los tests
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect