spring.application.name=servicio_de_agenda
server.port=8090
# Configuración de la base de datos
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@udpftr6a6yrxy6ye_high?TNS_ADMIN=C:/Wallet_Agenda
spring.datasource.username=ADMIN
spring.datasource.password=FullStack-001

# Por defecto, al levantar el proyecto normalmente, usar� 'dev' (Oracle)
spring.profiles.active=dev

# Configuraciones compartidas de documentaci�n
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html