spring.application.name=servicio_de_agenda
server.port=8081

# Por defecto, al levantar el proyecto normalmente, usará 'dev' (Oracle)
spring.profiles.active=dev

# Configuraciones compartidas de documentación
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html