spring:
  application:
    name: servicio_de_agenda
  profiles:
    active: dev

    

server:
  port: 8086

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
